stages:
  - build
  - test
  - container
  - helm chart

variables:
  # `showDateTime` will show the passed time in milliseconds. You need to specify `--batch-mode` to make this work.
  MAVEN_OPTS: >-
    -Dhttps.protocols=TLSv1.2
    -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository
    -Dorg.slf4j.simpleLogger.showDateTime=true
    -Djava.awt.headless=true

  # As of Maven 3.3.0 instead of this you MAY define these options in `.mvn/maven.config` so the same config is used
  # when running from the command line.
  # As of Maven 3.6.1, the use of `--no-tranfer-progress` (or `-ntp`) suppresses download and upload messages. The use
  # of the `Slf4jMavenTransferListener` is no longer necessary.
  # `installAtEnd` and `deployAtEnd` are only effective with recent version of the corresponding plugins.
  MAVEN_CLI_OPTS: >-
    --batch-mode
    --errors
    --fail-at-end
    --show-version
    --no-transfer-progress
    -DinstallAtEnd=true
    -DdeployAtEnd=true

image: maven:3-openjdk-17

# Cache downloaded dependencies and plugins between builds.
# To keep cache across branches add 'key: "$CI_JOB_NAME"'
# Be aware that `mvn deploy` will install the built jar into this repository. If you notice your cache size
# increasing, consider adding `-Dmaven.install.skip=true` to `MAVEN_OPTS` or in `.mvn/maven.config`
cache:
  paths:
    - .m2/repository

build:
  tags:
    - argus
  stage: build
  script:
    - mvn compile

test:
  tags:
    - argus
  stage: test
  script:
    - mvn test

build and publish docker image:
  tags:
    - argus
    - docker-image
  stage: container
  image:
    name: gcr.io/diamond-privreg/container-tools/kaniko-executor:v1.9.1-debug
    entrypoint: [ "" ]
  script:
    - echo 'Building image...'
    - env | grep "CI_"
    - /bin/sh ./kanikobuild.sh
    - echo "Done!"
  only:
    refs:
      - tags

publish helm chart:
  stage: helm chart
  tags:
    - argus
  image:
    name: gcr.io/diamond-pubreg/gda-core/nexus-helm-utils:latest
  script:
    - env | grep "CI_"
    - nexus-push helm/${CI_PROJECT_NAME} ${CI_COMMIT_TAG} ${CI_CHART_REGISTRY}
  only:
    refs:
      - tags
