apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: subscriptions
  title: Athena Subscriptions
  description: Emits publically visible events over Websockets/STOMP
  annotations:
    github.com/project-slug: DiamondLightSource/subscriptions
spec:
  type: service
  lifecycle: production
  owner: group:data-acquisition
  system: Athena
  providesApis:
    - subscriptions
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: subscriptions
  title: Athena Subscriptions
  description: Emits publically visible events over Websockets/STOMP
spec:
  type: asyncapi
  lifecycle: production
  owner: group:data-acquisition
  definition:
    $text: ./docs/user/reference/asyncapi.yaml
