server:
  port: 9020

connection:
  host: localhost
  port: 61613
  username: subscription
  password: M98CnVxB81AAy8xVheQ=
  destinations:
    - /topic/public
  filteredDestinations:
    - /app
  routingPrefix: /topic/

websocket:
  subscriptionEndpoint: /subscriptions