apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "subscriptions.fullname" . }}-spring-config
data:
  {{- with .Values.springConfig.config }}
application.yaml: |-
  {{- toYaml . | nindent 3 }}
  {{- end }}
