#Complete workflow to build, test, containerise and deploy the service

name: full

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ main ]

#env:
#  WORKFLOWS: ./.github/workflows

jobs:
  build-and-test:
    uses: ./.github/workflows/build.yaml
#  containerise:
#    needs: build-and-test
#    uses: $WORKFLOWS/container.yaml
#  helm-chart:
#    needs: containerise
#    uses: $WORKFLOWS/helm.yaml
