#Complete workflow to build, test, containerise and deploy the service

name: full

on:
  push:
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    uses: ./.github/workflows/build.yaml
  containerise:
    needs: build-and-test
    uses: ./.github/workflows/container.yaml
  helm-chart:
    needs: containerise
    uses: ./.github/workflows/helm.yaml
