# Validates the AsyncAPI

name: asyncapi_validate

on:
  workflow_call:

jobs:
  validate:

    runs-on: ubuntu-latest

    steps:
    - name: asyncapi-validate
      uses: WaleedAshraf/asyncapi-github-action@v0.0.10
      with:
        filepath: './docs/user/reference/asyncapi.yaml'
